### ISSUE TITLE
NullPointerException: Cannot invoke "mcjty.rftoolsbase.api.screens.data.IModuleDataString.get()" because "screenData" is null

### ISSUE THREAD

**Issue by pietro-lopes** [McJtyMods/RFToolsUtility#218]
Many players are reporting this kind of crash.

All the Mods 10 - 2.44 crashed. The logs have been uploaded to `gnomebot.dev`:
### Mod list changes beyond the modpack:
```ansi
[2;34mMod list wasn't modified.[0m
```

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Fixed next version

**Comment by Seriy500** [comment]
@McJty 
Still getting this error on 7.0.3

[debug.log](https://github.com/user-attachments/files/20272460/debug.log)
[latest.log](https://github.com/user-attachments/files/20272459/latest.log)

[crash-2025-05-18_15.46.25-client.txt](https://github.com/user-attachments/files/20272461/crash-2025-05-18_15.46.25-client.txt)
