### ISSUE TITLE
[7.0.5] Disconnect/crash when trying to view Screen Link in Tablet

### ISSUE THREAD

**Issue by Therrous** [McJtyMods/RFToolsUtility#228]
Modpack FTB Skies 2

Linking a screen in the player's base dimension, inserting the ScreenLink into a tablet, and then attempting to view the screen causes the disconnect

The screen has Energy, Time, and Text modules

Connection lost screen says:

> Failed to open a screen with advanced data:
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.getBlock()" because "p_155263_" is null

Relevant log entries pulled from debug
https://mclo.gs/LtdsvPV

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Should be fixed now

**Comment by Rav115** [comment]
in version RFToolsUtility - 1.21-7.0.6 
Doesn’t look fixed cause still getting this crash

> Client disconnected with reason: Failed to open a screen with advanced data: java.lang.NullPointerException: Cannot invoke 
> "net.minecraft.world.level.block.state.BlockState.getBlock()" because "p_155263_" is null

i only had tablet linked with screen tablet and screen only had Button module
even with only text module it still crashes client

> Client disconnected with reason: Failed to open a screen with advanced data: java.lang.NullPointerException

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
I can reproduce the problem. I will fix

**Comment by McJty** [comment]
Fixed next release

**Comment by RandumbPurson** [comment]
I'm on RFToolsUtility - 1.21-7.0.9 in the ATM10 modpack, and I got this same crash. Relevant logs [here](https://pastebin.com/422j5k5N).

EDIT: Looks like I just forgot to update McJtyLib, updating it to the latest version fixed the issue.
